### ISSUE TITLE
Warn when the `vendor` directory is not populated

### ISSUE THREAD

**Issue by hug-dev** [parallaxsecond/rust-psa-crypto#89] opened 2021-07-14 11:58 UTC
Just after freshly cloning the repo, the `vendor` directory needs to be populated with the git submodule. If one tries to compile, a cryptic error message is returned:

```
error: failed to run custom build command for `psa-crypto-sys v0.8.0 (/root/rust-psa-crypto/psa-crypto-sys)`

Caused by:
  process didn't exit successfully: `/root/rust-psa-crypto/target/debug/build/psa-crypto-sys-f27d8926d3ac59c9/build-script-build` (exit status: 1)
  --- stdout
  Did not find environment variables, building MbedTLS!
  cargo:rerun-if-changed=src/c/shim.c
  cargo:rerun-if-changed=src/c/shim.h

  --- stderr
  Error: Custom { kind: Other, error: "configuring mbedtls failed" }
```

We should try to improve the error message and also note in the README which command is needed.

**Comment by mcr** [comment] 2022-02-11 05:00
I also ran into this, particularly I'm not convinced that cargo knows to initialise sub-modules when rust-psa-crypto is a used as a dependency.

**Comment by ionut-arm** [comment] 2022-06-16 10:22
> particularly I'm not convinced that cargo knows to initialise sub-modules when rust-psa-crypto is a used as a dependency.

I think that was actually an issue with our release process. Cargo doesn't care about submodules in general, it just uploads stuff from your repo root folder - if you haven't checked out the submodule before publishing the crate you'll upload a crate without the submodule and with no way of fixing it 😬 oopsie! I'll check whether the latest versions of the PSA crate have this problem.

> I think this has been taken care of [here](https://github.com/parallaxsecond/rust-psa-crypto/pull/100/files#diff-8177766fe47397c3c76351ae290bf1f3e7c994a57f6664393f8201a05a9766cb)

Yeah, I think that's about right, just need to verify what we upstreamed to crates.io and then we can close this!

**Comment by ionut-arm** [comment] 2022-06-16 10:38
Ok, confirmed that no versions since 0.8.0 have this problem, and the newest version should warn of this problem explicitly. Closing for now, please comment if the issue appears again.

**Closed by ionut-arm** 2022-06-16 10:38 UTC
Labels: good first issue, small

**Comment by mcr** [comment] 2022-06-16 20:03
> I think this has been taken care of [here](https://github.com/parallaxsecond/rust-psa-crypto/pull/100/files#diff-8177766fe47397c3c76351ae290bf1f3e7c994a57f6664393f8201a05a9766cb) an error comes out `"MbedTLS config.py is missing. Have you run 'git submodule update --init'?"` The only missing part is adding a note to the README file to run `git submodule update --init` before build
> 
> Update: Overlooked! The README file contains a note on this under the "Notice" section "If you build the wrapper from source you need to run git submodule update --init after cloning the repository."
> 
> So I think this Issue can be closed

How often do you read the README of a dependancy of a dependancy?
If the contents come out of cargo, then I agree we are probably okay.
If the contents come out of git (from github), such as because one wants to test, *or CI* some fix, then I still think we need a clear message, or better, a way to get the right thing to happen.

**Comment by ionut-arm** [comment] 2022-06-17 08:41
> If the contents come out of cargo, then I agree we are probably okay.
> If the contents come out of git (from github), such as because one wants to test, or CI some fix, then I still think we need a clear message, or better, a way to get the right thing to happen.

That's true, but luckily the submodule does get included in the tarball for the crate - perhaps it was missing in an earlier version, but AFAIK it's there now!
